#!/bin/sh

##
# Runit run script for the development server daemon
#

# Ensure postgresql is running
sv start postgresql || exit 1

cd /var/www

# Start the rails server.
exec /sbin/setuser www-data bundle exec rails server
